/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.Consultas;

import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Roger
 */
public class Consulta1 extends javax.swing.JPanel {

    /**
     * Creates new form Consulta1
     */
    public Consulta1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaConsultaContainer = new javax.swing.JScrollPane();
        tablaConsulta = new javax.swing.JTable();

        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N. Alumno", "Curso", "N. + A. Prof.", "N. Apod."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaConsulta.getTableHeader().setReorderingAllowed(false);
        tablaConsultaContainer.setViewportView(tablaConsulta);
        if (tablaConsulta.getColumnModel().getColumnCount() > 0) {
            tablaConsulta.getColumnModel().getColumn(0).setResizable(false);
            tablaConsulta.getColumnModel().getColumn(1).setResizable(false);
            tablaConsulta.getColumnModel().getColumn(2).setResizable(false);
            tablaConsulta.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaConsultaContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaConsultaContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable tablaConsulta;
    private javax.swing.JScrollPane tablaConsultaContainer;
    // End of variables declaration//GEN-END:variables

    public JTable getTablaConsulta() {
        return tablaConsulta;
    }

    public void setTablaConsulta(JTable tablaConsulta) {
        this.tablaConsulta = tablaConsulta;
    }

    public JScrollPane getTablaConsultaContainer() {
        return tablaConsultaContainer;
    }

    public void setTablaConsultaContainer(JScrollPane tablaConsultaContainer) {
        this.tablaConsultaContainer = tablaConsultaContainer;
    }

    
}
