/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Roger
 */
public class Cursos extends javax.swing.JPanel {

    /**
     * Creates new form alumnos
     */
    public Cursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCurso = new javax.swing.JLabel();
        cmbCurso = new javax.swing.JComboBox<>();
        txtAnio = new javax.swing.JTextField();
        labelAnio = new javax.swing.JLabel();
        labelProfesores = new javax.swing.JLabel();
        tableProfesoresContainer = new javax.swing.JScrollPane();
        tableProfesores = new javax.swing.JTable();
        btnCrearCurso = new javax.swing.JButton();
        btnModificarCurso = new javax.swing.JButton();
        btnEliminarCurso = new javax.swing.JButton();
        cmbProfesor = new javax.swing.JComboBox<>();
        labelProfesor = new javax.swing.JLabel();
        btnAgregarProfesor = new javax.swing.JButton();
        btnEliminarProfesor = new javax.swing.JButton();
        cmbCargo = new javax.swing.JComboBox<>();
        labelCargo = new javax.swing.JLabel();
        btnModificarProfesor = new javax.swing.JButton();
        labelTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();

        labelCurso.setText("Curso:");

        cmbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtAnio.setText("jTextField1");

        labelAnio.setText("Año:");

        labelProfesores.setText("Profesores:");

        tableProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut", "Nombre", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProfesores.setShowGrid(false);
        tableProfesores.getTableHeader().setReorderingAllowed(false);
        tableProfesoresContainer.setViewportView(tableProfesores);
        if (tableProfesores.getColumnModel().getColumnCount() > 0) {
            tableProfesores.getColumnModel().getColumn(0).setResizable(false);
            tableProfesores.getColumnModel().getColumn(1).setResizable(false);
            tableProfesores.getColumnModel().getColumn(2).setResizable(false);
        }

        btnCrearCurso.setText("Crear Curso");
        btnCrearCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCursoActionPerformed(evt);
            }
        });

        btnModificarCurso.setText("Modificar Curso");
        btnModificarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCursoActionPerformed(evt);
            }
        });

        btnEliminarCurso.setText("Eliminar Curso");
        btnEliminarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCursoActionPerformed(evt);
            }
        });

        cmbProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelProfesor.setText("Profesor:");

        btnAgregarProfesor.setText("Agregar Profesor");
        btnAgregarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProfesorActionPerformed(evt);
            }
        });

        btnEliminarProfesor.setText("Eliminar Profesor");
        btnEliminarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProfesorActionPerformed(evt);
            }
        });

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelCargo.setText("Cargo:");

        btnModificarProfesor.setText("Modificar Profesor");
        btnModificarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProfesorActionPerformed(evt);
            }
        });

        labelTipo.setText("Tipo:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAnio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnio))
                    .addComponent(tableProfesoresContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCrearCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelProfesor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbProfesor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregarProfesor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarProfesor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbCurso)
                    .addComponent(labelCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbTipo)
                    .addComponent(labelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearCurso)
                    .addComponent(btnModificarCurso)
                    .addComponent(btnEliminarCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelProfesores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableProfesoresContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbProfesor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProfesor)
                    .addComponent(btnEliminarProfesor)
                    .addComponent(btnModificarProfesor))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearCursoActionPerformed

    private void btnModificarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarCursoActionPerformed

    private void btnEliminarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCursoActionPerformed

    private void btnAgregarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProfesorActionPerformed

    private void btnEliminarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarProfesorActionPerformed

    private void btnModificarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarProfesorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProfesor;
    private javax.swing.JButton btnCrearCurso;
    private javax.swing.JButton btnEliminarCurso;
    private javax.swing.JButton btnEliminarProfesor;
    private javax.swing.JButton btnModificarCurso;
    private javax.swing.JButton btnModificarProfesor;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JComboBox<String> cmbProfesor;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel labelAnio;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelCurso;
    private javax.swing.JLabel labelProfesor;
    private javax.swing.JLabel labelProfesores;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JTable tableProfesores;
    private javax.swing.JScrollPane tableProfesoresContainer;
    private javax.swing.JTextField txtAnio;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgregarProfesor() {
        return btnAgregarProfesor;
    }

    public void setBtnAgregarProfesor(JButton btnAgregarProfesor) {
        this.btnAgregarProfesor = btnAgregarProfesor;
    }

    public JButton getBtnCrearCurso() {
        return btnCrearCurso;
    }

    public void setBtnCrearCurso(JButton btnCrearCurso) {
        this.btnCrearCurso = btnCrearCurso;
    }

    public JButton getBtnEliminarCurso() {
        return btnEliminarCurso;
    }

    public void setBtnEliminarCurso(JButton btnEliminarCurso) {
        this.btnEliminarCurso = btnEliminarCurso;
    }

    public JButton getBtnEliminarProfesor() {
        return btnEliminarProfesor;
    }

    public void setBtnEliminarProfesor(JButton btnEliminarProfesor) {
        this.btnEliminarProfesor = btnEliminarProfesor;
    }

    public JButton getBtnModificarCurso() {
        return btnModificarCurso;
    }

    public void setBtnModificarCurso(JButton btnModificarCurso) {
        this.btnModificarCurso = btnModificarCurso;
    }

    public JButton getBtnModificarProfesor() {
        return btnModificarProfesor;
    }

    public void setBtnModificarProfesor(JButton btnModificarProfesor) {
        this.btnModificarProfesor = btnModificarProfesor;
    }

    public JComboBox<String> getCmbCargo() {
        return cmbCargo;
    }

    public void setCmbCargo(JComboBox<String> cmbCargo) {
        this.cmbCargo = cmbCargo;
    }

    public JComboBox<String> getCmbCurso() {
        return cmbCurso;
    }

    public void setCmbCurso(JComboBox<String> cmbCurso) {
        this.cmbCurso = cmbCurso;
    }

    public JComboBox<String> getCmbProfesor() {
        return cmbProfesor;
    }

    public void setCmbProfesor(JComboBox<String> cmbProfesor) {
        this.cmbProfesor = cmbProfesor;
    }

    public JComboBox<String> getCmbTipo() {
        return cmbTipo;
    }

    public void setCmbTipo(JComboBox<String> cmbTipo) {
        this.cmbTipo = cmbTipo;
    }

    public JLabel getLabelAnio() {
        return labelAnio;
    }

    public void setLabelAnio(JLabel labelAnio) {
        this.labelAnio = labelAnio;
    }

    public JLabel getLabelCargo() {
        return labelCargo;
    }

    public void setLabelCargo(JLabel labelCargo) {
        this.labelCargo = labelCargo;
    }

    public JLabel getLabelCurso() {
        return labelCurso;
    }

    public void setLabelCurso(JLabel labelCurso) {
        this.labelCurso = labelCurso;
    }

    public JLabel getLabelProfesor() {
        return labelProfesor;
    }

    public void setLabelProfesor(JLabel labelProfesor) {
        this.labelProfesor = labelProfesor;
    }

    public JLabel getLabelProfesores() {
        return labelProfesores;
    }

    public void setLabelProfesores(JLabel labelProfesores) {
        this.labelProfesores = labelProfesores;
    }

    public JLabel getLabelTipo() {
        return labelTipo;
    }

    public void setLabelTipo(JLabel labelTipo) {
        this.labelTipo = labelTipo;
    }

    public JTable getTableProfesores() {
        return tableProfesores;
    }

    public void setTableProfesores(JTable tableProfesores) {
        this.tableProfesores = tableProfesores;
    }

    public JScrollPane getTableProfesoresContainer() {
        return tableProfesoresContainer;
    }

    public void setTableProfesoresContainer(JScrollPane tableProfesoresContainer) {
        this.tableProfesoresContainer = tableProfesoresContainer;
    }

    public JTextField getTxtAnio() {
        return txtAnio;
    }

    public void setTxtAnio(JTextField txtAnio) {
        this.txtAnio = txtAnio;
    }
}
